---
- name: Get Jenkins crumb
  uri:
    url: '{{ jenkins_jobs_server_url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
    user: "{{ jenkins_jobs_server_user }}"
    password: "{{ jenkins_jobs_server_password }}"
    force_basic_auth: yes
    return_content: yes
  register: crumb

- name: Remove credential
  uri:
    method: POST
    url: '{{ jenkins_jobs_server_url }}/credentials/store/system/domain/_/credential/{{ credentials.id }}/doDelete'
    user: "{{ jenkins_jobs_server_user }}"
    password: "{{ jenkins_jobs_server_password }}"
    force_basic_auth: yes
    return_content: yes
    status_code: 302, 404
    headers:
      Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"

- name: Create username/password credential
  when: credentials.state | default('present') != 'absent' and credentials.ssh_private_key is not defined
  uri:
    method: POST
    url: '{{ jenkins_jobs_server_url }}/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkins_jobs_server_user }}"
    password: "{{ jenkins_jobs_server_password }}"
    force_basic_auth: yes
    return_content: yes
    status_code: 302
    headers:
      Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "{{ credentials.id }}",
          "username": {{ credentials.username | default('') | to_json | urlencode }},
          "password": {{ credentials.password | default('') | to_json | urlencode }},
          "description": {{ credentials.description | default('') | to_json | urlencode }},
          "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
        }
      }

- name: Create SSH key credential
  when: credentials.state | default('present') != 'absent' and credentials.ssh_private_key is defined
  uri:
    method: POST
    url: '{{ jenkins_jobs_server_url }}/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkins_jobs_server_user }}"
    password: "{{ jenkins_jobs_server_password }}"
    force_basic_auth: yes
    return_content: yes
    status_code: 302
    headers:
      Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
    body: >
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "{{ credentials.id }}",
          "username": {{ credentials.username | default('') | to_json | urlencode }},
          "passphrase": {{ credentials.password | default('') | to_json | urlencode }},
          "description": {{ credentials.description | default('') | to_json | urlencode }},
          "privateKeySource": {
            "$class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource",
            "privateKey": {{ credentials.ssh_private_key | to_json | urlencode }}
          },
          "$class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"
        }
      }

